server:
  port: 8087
  
spring:
  profiles:
    active: stage

message: STAGE ENV

startRoute: timer:hello-stage?period=1000
fromRoute:  file:data/input?delete=true&readLock=none
toRoute1: file:data/output