server:
  port: 8087
  
spring:
  profiles:
    active: dev

message: DEV ENV
    
startRoute: timer:hello-dev?period=1000
fromRoute:  file:data/input?delete=true&readLock=none
toRoute1: file:data/output