server:
  port: 8087
  
spring:
  profiles:
    active: prod

message: PROD ENV

startRoute: timer:hello-prod?period=1000
fromRoute:  file:data/input?delete=true&readLock=none
toRoute1: file:data/output
